In [1]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
import scipy.stats
import math
from sklearn.utils import shuffle
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix,precision_score, recall_score, f1_score ,accuracy_score

# List of file names
file_names = [
    '/content/0.7inner-100watt.csv', '/content/0.7outer-100watt.csv',
    '/content/0.7inner-200watt.csv', '/content/0.7outer-200watt.csv',
    '/content/0.7inner-300watt.csv', '/content/0.7outer-300watt.csv',
    '/content/0.9inner-100watt.csv', '/content/0.9outer-100watt.csv',
    '/content/0.9inner-200watt.csv', '/content/0.9outer-200watt.csv',
    '/content/0.9inner-300watt.csv', '/content/0.9outer-300watt.csv',
    '/content/1.1inner-100watt.csv', '/content/1.1outer-100watt.csv',
    '/content/1.1inner-200watt.csv', '/content/1.1outer-200watt.csv',
    '/content/1.1inner-300watt.csv', '/content/1.1outer-300watt.csv',
    '/content/1.3inner-100watt.csv', '/content/1.3outer-100watt.csv',
    '/content/1.3inner-200watt.csv', '/content/1.3outer-200watt.csv',
    '/content/1.3inner-300watt.csv', '/content/1.3outer-300watt.csv',
    '/content/1.5inner-100watt.csv', '/content/1.5outer-100watt.csv',
    '/content/1.5inner-200watt.csv', '/content/1.5outer-200watt.csv',
    '/content/1.5inner-300watt.csv', '/content/1.5outer-300watt.csv',
    '/content/1.7inner-100watt.csv', '/content/1.7outer-100watt.csv',
    '/content/1.7inner-200watt.csv', '/content/1.7outer-200watt.csv',
    '/content/1.7inner-300watt.csv', '/content/1.7outer-300watt.csv',
    '/content/BRB-12-4-100watt.csv', '/content/BRB-12-4-300watt.csv'
    ,'/content/healthy.csv'
]

# Initialize an empty DataFrame to store the reshaped data
combined_reshaped_data = pd.DataFrame()

# Iterate over the list of file names
for file_name in file_names:
    # Read the CSV file
    data = pd.read_csv(file_name)
    label = file_name.split('/')[-1].split('-')[0]  # Extract the label from the file name

    # Select the "Current-A" column
    current_a_column = data[' Current-A']

    # Transpose the "Current-A" column
    transposed_current_a = current_a_column.head(100000).values.reshape(1, -1)

    # Reshape the transposed "Current-A" column into blocks of 1000 columns for each row
    block_size = 1000
    num_blocks = transposed_current_a.shape[1] // block_size
    reshaped_current_a = transposed_current_a[:, :num_blocks * block_size].reshape(-1, block_size)

    # Create a DataFrame from the reshaped "Current-A" column
    reshaped_current_a_df = pd.DataFrame(reshaped_current_a, columns=[f'Block_{i+1}' for i in range(block_size)])

    # Add a new column 'Label' with the corresponding label for each row
    reshaped_current_a_df['Label'] = label

    # Append the reshaped data to the combined DataFrame
    combined_reshaped_data = combined_reshaped_data.append(reshaped_current_a_df, ignore_index=True)

# Save the combined reshaped data to a new CSV file
a = combined_reshaped_data.to_csv('/content/final_combined.csv', index=False)

# Display the combined reshaped DataFrame
print(combined_reshaped_data)
combined_reshaped_data.shape

<ipython-input-1-c4d973503f12>:62: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  combined_reshaped_data = combined_reshaped_data.append(reshaped_current_a_df, ignore_index=True)
<ipython-input-1-c4d973503f12>:62: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  combined_reshaped_data = combined_reshaped_data.append(reshaped_current_a_df, ignore_index=True)
<ipython-input-1-c4d973503f12>:62: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  combined_reshaped_data = combined_reshaped_data.append(reshaped_current_a_df, ignore_index=True)
<ipython-input-1-c4d973503f12>:62: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  combined_reshaped_data = comb

      Block_1  Block_2  Block_3  Block_4  Block_5  Block_6  Block_7  Block_8  \
0      2.3309   2.3309   2.3309   2.3309   2.3309   2.3309   2.3309   2.3309   
1      2.7228   2.7228   2.7228   2.7228   2.7228   2.7228   2.7228   2.7228   
2      2.9524   2.9524   2.9524   2.9524   2.9524   2.9524   2.9524   2.9524   
3      2.1111   2.1111   2.1111   2.1111   2.1111   2.1111   2.1111   2.1111   
4      2.1282   2.1282   2.1282   2.1282   2.1282   2.1282   2.1282   2.1282   
...       ...      ...      ...      ...      ...      ...      ...      ...   
2519   2.4603   2.4530   2.4530   2.4530   2.4530   2.4530   2.4530   2.4530   
2520   2.3712   2.3712   2.3712   2.3712   2.3712   2.3712   2.3712   2.3712   
2521   2.3065   2.3065   2.3065   2.3065   2.3065   2.3065   2.3065   2.3065   
2522   2.2552   2.2552   2.2552   2.2552   2.2552   2.2552   2.2552   2.2552   
2523   2.2479   2.2479   2.2479   2.2479   2.2479   2.2479   2.2479   2.2479   

      Block_9  Block_10  ...  Block_992

(2524, 1001)

In [ ]:
import pandas as pd
import numpy as np
df = pd.read_csv("/content/final_combined.csv",low_memory=False,header=None)
df = pd.DataFrame(df)

df = df.dropna(axis = 0)
print(df.isnull().sum(axis = 0))


# Load the combined data
file_path = '/content/final_combined.csv'
combined_data = pd.read_csv(file_path, header=None)

# Replace non-numeric values with NaN
combined_data = combined_data.apply(pd.to_numeric, errors='coerce')

# Drop rows with NaN values
combined_data = combined_data.dropna()

# Extract labels and data without labels
labels = combined_data.iloc[:, -1]
features = combined_data.iloc[:, :-1].to_numpy(dtype=float)

# Function to calculate Euclidean distance between two points
def euclidean_distance(x1, x2):
    return np.sqrt(np.sum((x1 - x2) ** 2))

# Function to calculate Euclidean distance matrix for all points
def euclidean_distance_matrix(features):
    num_points = len(features)
    distance_matrix = np.zeros((num_points, num_points))

    for i in range(num_points):
        for j in range(num_points):
            distance_matrix[i, j] = euclidean_distance(features[i, :], features[j, :])

    return distance_matrix

# Calculate the Euclidean distance matrix
distance_matrix = euclidean_distance_matrix(features)

# Print or use the distance matrix as needed
print(distance_matrix)
print(distance_matrix.shape)


0       0
1       0
2       0
3       0
4       0
       ..
996     0
997     0
998     0
999     0
1000    0
Length: 1001, dtype: int64


<ipython-input-48-ce7bdd4decac>:12: DtypeWarning: Columns (9,21,41,51,115,144,175,177,178,190,227,243,273,299,348,366,409,416,423,520,541,556,560,571,658,743,745,761,796,826,832,863,888,910,975,989) have mixed types. Specify dtype option on import or set low_memory=False.
  combined_data = pd.read_csv(file_path, header=None)


[]
(0, 0)


In [3]:
final = pd.read_csv('/content/final_combined.csv')
Fdf = pd.DataFrame(final)
Fdf.shape

(2524, 1001)

In [4]:
# Load your data from the file
file_path = '/content/final_combined.csv'  # Replace with the actual path to your file
data = pd.read_csv(file_path)

# Extract labels and data without labels
labels = data.iloc[:, -1]
features = data.iloc[:, :-1].to_numpy()  # Convert to numpy array

# Function to calculate Euclidean distance matrix for all points
def euclidean_distance_matrix(features):
    num_points = len(features)
    distance_matrix = np.zeros((num_points, num_points))

    for i in range(num_points):
        for j in range(num_points):
            distance_matrix[i, j] = np.linalg.norm(features[i, :] - features[j, :])

    return distance_matrix

# Calculate the Euclidean distance matrix
distance_matrix = euclidean_distance_matrix(features)

# Print or use the distance matrix as needed
print(distance_matrix)
distance_matrix.shape


[[ 0.         21.7419321  16.73495203 ...  7.5739908   7.44013472
   6.9330108 ]
 [21.7419321   0.         16.99134181 ... 22.01010913 22.96423552
  22.43775441]
 [16.73495203 16.99134181  0.         ... 11.71534555 12.7376965
  12.68142327]
 ...
 [ 7.5739908  22.01010913 11.71534555 ...  0.          1.08831266
   1.01131289]
 [ 7.44013472 22.96423552 12.7376965  ...  1.08831266  0.
   0.67889333]
 [ 6.9330108  22.43775441 12.68142327 ...  1.01131289  0.67889333
   0.        ]]


(2524, 2524)

In [10]:
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score

class knn:
    def __init__(self, k=3):
        self.k = k
        self.X_train = None
        self.y_train = None

    def fit(self, X_train, y_train):
        self.X_train = X_train
        self.y_train = y_train
    def predict(self, X_test):
        predictions = []
        final_prediction = []
        for i in range(len(X_test)):
            distances = [self.euclidean_distance(X_test[i], x) for x in self.X_train]
            nearest_indices = np.argsort(distances)[:self.k]
            nearest_labels = [self.y_train[idx] for idx in nearest_indices]
            predicted_label = self.most_common(nearest_labels)
            predictions.append(predicted_label)
        return predictions



    def euclidean_distance(self, x1, x2):
        return np.sqrt(np.sum((x1 - x2) ** 2))

    def most_common(self, lst):
        unique, counts = np.unique(lst, return_counts=True)
        index = np.argmax(counts)
        return unique[index]

X = final.iloc[:, :-1].values  # Assuming the last column is the target variable
y = final.iloc[:, -1].values
X_train,X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
print(len(X_train[0]))
model = knn(k=5)
model.fit(X_train, y_train)
# Make predictions on the test set
predictions = model.predict(X_test)
# Display the predictions

print(len(predictions))
print(len(X_test))

print(predictions)
accuracy = accuracy_score(y_test, predictions)
print(f"Accuracy: {accuracy * 100:.2f}%")

1000
505
505
['0.9inner', '1.1inner', '0.7inner', '0.7inner', '0.7inner', '0.9outer', '0.9inner', '0.7inner', '0.7inner', '0.9inner', '1.5inner', '0.7inner', '0.9outer', '1.3inner', '1.3outer', '0.9inner', 'BRB', '0.7inner', '0.7inner', '0.7inner', '1.1inner', '1.1outer', '0.9outer', '1.3inner', '0.9outer', '1.1inner', '0.7outer', '0.7inner', '1.3inner', '1.1inner', '0.9outer', '1.1outer', '0.7outer', '1.3inner', '0.9outer', '0.7inner', '0.7outer', '0.9outer', '0.9outer', '0.7outer', '0.7inner', '0.9outer', '1.1outer', '1.7inner', '0.7inner', '0.7outer', '0.9outer', '0.9inner', '0.7inner', '0.7outer', '1.3outer', '1.1inner', '0.9inner', '0.9outer', 'healthy.csv', '1.1outer', '0.7inner', '0.7outer', '0.9inner', '0.7outer', '1.3inner', '0.7outer', '0.7inner', '0.7inner', '0.7outer', '0.9inner', '1.5inner', '0.9inner', '0.9outer', '1.3inner', '1.1inner', '0.9outer', '0.7inner', '0.9inner', '1.1outer', '0.7outer', '0.9inner', '0.7inner', '1.1inner', '1.3outer', '0.7inner', '0.7outer', '1.1

In [12]:
import random

def hold_out(X, y, test_size=0.2, random_seed=None):
    if random_seed:
        random.seed(random_seed)

    data = list(zip(X, y))
    random.shuffle(data)

    split_index = int(len(data) * (1 - test_size))
    train_data, test_data = data[:split_index], data[split_index:]

    X_train, y_train = zip(*train_data)
    X_test, y_test = zip(*test_data)

    return X_train, X_test, y_train, y_test

# Usage
X_train, X_test, y_train, y_test = hold_out(X, y, test_size=0.2, random_seed=42)
model = knn(k=5)
model.fit(X_train, y_train)
# Make predictions on the test set
predictions = model.predict(X_test)
# Display the predictions
print(len(predictions))
print(len(y_test))
accuracy = accuracy_score(y_test, predictions)
print(f"Accuracy: {accuracy * 100:.2f}%")

505
505
Accuracy: 25.15%


In [13]:
import numpy as np

def fold_validation(X, y, k=2):
    data = list(zip(X, y))
    np.random.shuffle(data)

    fold_size = len(data) // k
    folds = [data[i:i + fold_size] for i in range(0, len(data), fold_size)]

    for i in range(k):
        test_data = folds[i]
        train_data = [item for j in range(k) if j != i for item in folds[j]]

        X_train, y_train = zip(*train_data)
        X_test, y_test = zip(*test_data)

        yield np.array(X_train), np.array(X_test), np.array(y_train), np.array(y_test)

# Example usage:

accuracies = []
for X_train, X_test, y_train, y_test in fold_validation(X, y,2):
    model = knn(k=5)
    model.fit(X_train, y_train)

    predictions = model.predict(X_test)

    accuracy = accuracy_score(y_test, predictions)
    accuracies.append(accuracy)
    print(accuracy)
overall_accuracy = np.mean(accuracies)
print(f"Overall Accuracy: {overall_accuracy * 100:.2f}%")


0.2179080824088748
0.2115689381933439
Overall Accuracy: 21.47%


In [14]:
accuracy = accuracy_score(y_test, predictions)
precision = precision_score(y_test, predictions, average='weighted')
recall = recall_score(y_test, predictions, average='weighted')
f1 = f1_score(y_test, predictions, average='weighted')

# Confusion matrix
conf_matrix = confusion_matrix(y_test, predictions)

# Display the results
print(f"Accuracy: {accuracy * 100:.2f}%")
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")
print(f"F1 Score: {f1:.2f}")
print("Confusion Matrix:")
print(conf_matrix)

Accuracy: 21.16%
Precision: 0.22
Recall: 0.21
F1 Score: 0.20
Confusion Matrix:
[[61 12 12 24  3 12  6  5  2  2  0  1  1  0]
 [39 36 10 30  5  2  1  6  4  1  1  0  0  1]
 [25  4 43  6 24 12 17  4  0  4  2  5  0  9]
 [68 17  8 34  2  3  3  4  3  2  1  0  0  0]
 [12 12 33  9 14  7  2  0  1  2  0  3  0 11]
 [28  9 16  9  9 12  9  5  1  4  0  1  0  0]
 [ 5  8 29  3 20  7 17  8  1  3  1  2  0  4]
 [19  7 12 10  7  7  9  6  3  2  1  1  0  3]
 [13 12  7  3  5  0  0  3  3  2  0  0  0  1]
 [ 9  7 10  4  4  0  3  3  0  8  0  1  0  1]
 [ 8  3 10  3  5  2  4  2  4  1  2  2  0  1]
 [ 3  1 13  0 11  3  7  2  0  1  0  6  0  5]
 [12  3  7  2  3  1  3  3  1  1  0  0  1  3]
 [ 2  0  5  0  7  3  2  0  0  0  0  0  0 24]]


In [17]:
# Given Confusion Matrix
conf_matrix = np.array([[61, 12, 12, 24, 3, 12, 6, 5, 2, 2, 0, 1, 1, 0],
                       [39, 36, 10, 30, 5, 2, 1, 6, 4, 1, 1, 0, 0, 1],
                       [25, 4, 43, 6, 24, 12, 17, 4, 0, 4, 2, 5, 0, 9],
                       [68, 17, 8, 34, 2, 3, 3, 4, 3, 2, 1, 0, 0, 0],
                       [12, 12, 33, 9, 14, 7, 2, 0, 1, 2, 0, 3, 0, 11],
                       [28, 9, 16, 9, 9, 12, 9, 5, 1, 4, 0, 1, 0, 0],
                       [5, 8, 29, 3, 20, 7, 17, 8, 1, 3, 1, 2, 0, 4],
                       [19, 7, 12, 10, 7, 7, 9, 6, 3, 2, 1, 1, 0, 3],
                       [13, 12, 7, 3, 5, 0, 0, 3, 3, 2, 0, 0, 0, 1],
                       [9, 7, 10, 4, 4, 0, 3, 3, 0, 8, 0, 1, 0, 1],
                       [8, 3, 10, 3, 5, 2, 4, 2, 4, 1, 2, 2, 0, 1],
                       [3, 1, 13, 0, 11, 3, 7, 2, 0, 1, 0, 6, 0, 5],
                       [12, 3, 7, 2, 3, 1, 3, 3, 1, 1, 0, 0, 1, 3],
                       [2, 0, 5, 0, 7, 3, 2, 0, 0, 0, 0, 0, 0, 24]])

# Extract values from the confusion matrix
true_positive = np.diag(conf_matrix)
false_positive = np.sum(conf_matrix, axis=0) - true_positive
false_negative = np.sum(conf_matrix, axis=1) - true_positive
true_negative = np.sum(conf_matrix) - (true_positive + false_positive + false_negative)

# Calculate Sensitivity (Recall)
sensitivity = true_positive / (true_positive + false_negative)

# Calculate Specificity
specificity = true_negative / (true_negative + false_positive)

# Display the results
print(f"Sensitivity (Recall): {sensitivity}")
print(f"Specificity: {specificity}")


Sensitivity (Recall): [0.43262411 0.26470588 0.27741935 0.23448276 0.13207547 0.11650485
 0.15740741 0.06896552 0.06122449 0.16       0.04255319 0.11538462
 0.025      0.55813953]
Specificity: [0.78322926 0.91563055 0.84462511 0.90778872 0.90916955 0.94909405
 0.94280763 0.96170213 0.98351195 0.97937294 0.99506173 0.98677686
 0.99918167 0.96800656]


In [49]:
# Function to perform PCA
def perform_pca(X, num_components):
    # Center the data
    mean_vector = np.mean(X, axis=0)
    centered_data = X - mean_vector

    # Calculate the covariance matrix
    covariance_matrix = np.cov(centered_data, rowvar=False)

    # Calculate the eigenvalues and eigenvectors
    eigenvalues, eigenvectors = np.linalg.eigh(covariance_matrix)

    # Sort eigenvectors based on eigenvalues
    sorted_indices = np.argsort(eigenvalues)[::-1]
    sorted_eigenvectors = eigenvectors[:, sorted_indices]

    # Select the top 'num_components' eigenvectors
    selected_eigenvectors = sorted_eigenvectors[:, :num_components]

    # Project the data onto the selected eigenvectors
    pca_data = centered_data.dot(selected_eigenvectors)

    return pca_data

X = final.iloc[:, :-1].values  # Features
labels = final.iloc[:, -1].values
# Center the data (subtract mean)
X_centered = X - np.mean(X, axis=0)

# Apply PCA
n_components = 500  # Adjust the number of components as needed
X_pca = perform_pca(X_centered, n_components)

# Display the result
print("Original shape:", X.shape)
print("PCA transformed shape:", X_pca.shape)


Original shape: (2524, 1000)
PCA transformed shape: (2524, 500)


In [50]:
labels = pd.DataFrame(labels)
df_pca = pd.DataFrame(X_pca)
df_pca = pd.concat([df_pca, labels], axis=1)
df_pca

0         1         2         3         4         5         6    \
0      5.955241 -6.123423  1.392737 -1.004516  1.445286  0.303847 -0.098025   
1    -15.298333 -2.266847  0.740394  0.394430 -0.104173  0.108850  0.055378   
2     -2.112004  8.352890  0.620439 -0.886738 -0.251630  0.080444 -0.067001   
3     15.428373 -0.255818 -1.277459 -0.165317  0.016419 -0.149794 -0.054500   
4     -3.434053 -7.976184 -0.120620  1.391388  0.008688  0.100361 -0.191144   
...         ...       ...       ...       ...       ...       ...       ...   
2519   2.319843  0.837512 -0.471465 -0.074975 -0.029233 -0.000439  0.014350   
2520   4.573273  0.748433 -0.932019 -0.076154 -0.056432  0.024462 -0.005447   
2521   6.419987  0.620494 -1.281355 -0.065643 -0.047337  0.028284  0.014502   
2522   7.415206  0.229961 -1.475239 -0.031230 -0.058852  0.018948  0.005620   
2523   6.943346 -0.229939 -1.349943  0.058970 -0.069479  0.023171  0.002071   

           7         8         9    ...       491       492       493  \
0     0.262480  0.154173  0.258820  ...  0.003862 -0.004207  0.001941   
1     0.085530 -0.005836  0.037211  ... -0.002865 -0.000168 -0.000779   
2     0.031550  0.103155 -0.046293  ...  0.002821 -0.004588  0.003449   
3     0.047318  0.090442 -0.146929  ... -0.003407 -0.001280 -0.002649   
4    -0.041205  0.042227  0.148734  ...  0.005562  0.010288  0.007877   
...        ...       ...       ...  ...       ...       ...       ...   
2519  0.006720  0.036565 -0.013350  ...  0.000328  0.000231  0.000463   
2520  0.004837  0.023221  0.002441  ...  0.000562 -0.000158 -0.000453   
2521  0.018135  0.020402 -0.014236  ... -0.000232 -0.000144 -0.000072   
2522  0.007761  0.012863 -0.004040  ...  0.000501  0.000445 -0.000163   
2523  0.020988  0.016486  0.004069  ... -0.000512 -0.000081 -0.000073   

           494       495       496       497       498       499          0    
0    -0.004074 -0.002205  0.000166  0.003739  0.001948  0.005690     0.7inner  
1     0.003110 -0.001612  0.003418  0.000808  0.004798  0.001647     0.7inner  
2     0.002830  0.001180 -0.005121  0.003963 -0.000060  0.003464     0.7inner  
3     0.006698  0.002035 -0.001648  0.000424 -0.001228  0.000495     0.7inner  
4    -0.009217 -0.006279  0.000194 -0.000811  0.000824  0.006790     0.7inner  
...        ...       ...       ...       ...       ...       ...          ...  
2519 -0.000644  0.000219 -0.000237  0.000664  0.000455 -0.000919  healthy.csv  
2520  0.000445 -0.001283 -0.000908  0.001058 -0.000110 -0.000463  healthy.csv  
2521 -0.000113 -0.001257  0.000528 -0.000041 -0.000129 -0.000743  healthy.csv  
2522  0.000086 -0.000387 -0.000208 -0.000016 -0.000077 -0.000371  healthy.csv  
2523  0.000782 -0.000365  0.000161  0.000315  0.000371 -0.000611  healthy.csv  

[2524 rows x 501 columns]

In [51]:

X_pca = df_pca.iloc[:, :-1].values  # Assuming the last column is the target variable
y_pca = df_pca.iloc[:, -1].values
X_train,X_test, y_train, y_test = train_test_split(X_pca, y_pca, test_size=0.2, random_state=42)
print(len(X_train[0]))
model = knn(k=5)
model.fit(X_train, y_train)
# Make predictions on the test set
predictions = model.predict(X_test)
# Display the predictions

print(len(predictions))
print(len(X_test))

print(predictions)
accuracy = accuracy_score(y_test, predictions)
print(f"Accuracy: {accuracy * 100:.2f}%")

500
505
505
['0.9inner', '1.1inner', '0.7inner', '0.7inner', '0.7inner', '0.9outer', '0.9inner', '0.7inner', '0.7inner', '0.9inner', '1.5inner', '0.7inner', '0.9outer', '1.3inner', '1.3outer', '0.9inner', 'BRB', '0.7inner', '0.7inner', '0.7inner', '1.1inner', '1.1outer', '0.9outer', '1.3inner', '0.9outer', '1.1inner', '0.7outer', '0.7inner', '1.3inner', '1.1inner', '0.9outer', '1.1outer', '0.7outer', '1.3inner', '0.9outer', '0.7inner', '0.7outer', '0.9outer', '0.9outer', '0.7outer', '0.7inner', '0.9outer', '1.1outer', '1.7inner', '0.7inner', '0.7outer', '0.9outer', '0.9inner', '0.7inner', '0.7outer', '1.3outer', '1.1inner', '0.9inner', '0.9outer', 'healthy.csv', '1.1outer', '0.7inner', '0.7outer', '0.9inner', '0.7outer', '1.3inner', '0.7outer', '0.7inner', '0.7inner', '0.7outer', '0.9inner', '1.5inner', '0.9inner', '0.9outer', '1.3inner', '1.1inner', '0.9outer', '0.7inner', '0.9inner', '1.1outer', '0.7outer', '0.9inner', '0.7inner', '1.1inner', '1.3outer', '0.7inner', '0.7outer', '1.1i

In [52]:

X_pca = df_pca.iloc[:, :-1].values  # Assuming the last column is the target variable
y_pca = df_pca.iloc[:, -1].values
X_train,X_test, y_train, y_test = hold_out(X_pca, y_pca, test_size=0.2)
print(len(X_train[0]))
model = knn(k=5)
model.fit(X_train, y_train)
# Make predictions on the test set
predictions = model.predict(X_test)
# Display the predictions

print(len(predictions))
print(len(X_test))

print(predictions)
accuracy = accuracy_score(y_test, predictions)
print(f"Accuracy: {accuracy * 100:.2f}%")

500
505
505
['0.7outer', '0.7outer', '0.7outer', '0.7inner', '0.7outer', '1.1inner', '1.3outer', '0.9inner', '0.9outer', '0.9outer', '0.9inner', '0.9inner', '0.7inner', '0.7inner', 'healthy.csv', '0.9inner', '0.7inner', '0.9inner', '0.9inner', '0.7inner', '0.9inner', '0.9inner', '0.7outer', 'healthy.csv', '0.7inner', '0.9inner', '0.9inner', '0.7inner', '0.7inner', '1.3inner', '0.7outer', '0.7outer', '1.1inner', '0.7inner', '1.3inner', '1.7inner', 'BRB', '0.7inner', '1.7outer', '1.1inner', '1.1outer', '1.3inner', '0.7outer', '1.1inner', '1.1inner', '1.1outer', '0.7inner', '1.3inner', '0.7outer', '0.9inner', '1.7inner', '1.3inner', '0.7inner', '0.7inner', 'BRB', '1.1inner', '0.7outer', '0.7inner', '0.7outer', '0.7inner', '0.9inner', '1.1outer', '0.7inner', '0.7outer', '1.5outer', '1.3inner', '0.9inner', 'BRB', '1.1outer', '1.3outer', '1.3inner', '1.1inner', '0.9outer', '0.7inner', '1.1outer', '1.5outer', '0.9inner', '0.9outer', '0.9outer', '1.3outer', '1.7inner', '0.9inner', '1.7inner', 

In [32]:
accuracies = []
for X_train, X_test, y_train, y_test in fold_validation(X, y,2):
    model = knn(k=5)
    model.fit(X_train, y_train)

    # Make predictions on the test set
    predictions = model.predict(X_test)

    # Display the predictions
    # print(predictions)

    accuracy = accuracy_score(y_test, predictions)
    accuracies.append(accuracy)
    print(accuracy)
overall_accuracy = np.mean(accuracies)
print(f"Overall Accuracy: {overall_accuracy * 100:.2f}%")


0.22107765451664024
0.2091917591125198
Overall Accuracy: 21.51%


In [35]:
accuracy = accuracy_score(y_test, predictions)
precision = precision_score(y_test, predictions, average='weighted')
recall = recall_score(y_test, predictions, average='weighted')
f1 = f1_score(y_test, predictions, average='weighted')

# Confusion matrix
conf_matrix = confusion_matrix(y_test, predictions)

# Display the results
print(f"Accuracy: {accuracy * 100:.2f}%")
print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")
print(f"F1 Score: {f1:.2f}")
print("Confusion Matrix:")
print(conf_matrix)

Accuracy: 25.15%
Precision: 0.28
Recall: 0.25
F1 Score: 0.24
Confusion Matrix:
[[26  8  3  5  3  4  4  3  0  0  0  1  1  0]
 [16 15  4  8  2  1  1  3  2  2  0  0  1  0]
 [13  4 19  1  6  4  7  3  0  0  1  3  0  1]
 [31  8  2 25  0  0  0  0  1  0  0  2  0  0]
 [ 6  5  7  4  4  3  2  0  0  0  0  1  0  0]
 [18  2  6  4  3  5  1  0  0  0  0  0  0  0]
 [ 4  2 11  2  2  2 12  0  2  0  0  1  0  1]
 [ 5  1  5  5  3  6  5  5  0  0  0  1  0  0]
 [ 6  5  0  5  1  1  0  1  2  3  0  0  0  0]
 [ 6  5  6  1  0  0  0  0  1  3  0  1  0  0]
 [ 5  2  6  3  2  1  2  1  1  1  1  0  0  0]
 [ 2  2  2  1  4  1  2  1  0  0  0  5  0  1]
 [ 2  3  3  0  0  0  0  1  1  0  0  0  0  0]
 [ 0  0  1  0  4  0  2  0  0  0  0  0  0  5]]


In [39]:
confusion_matrix = np.array([[26, 8, 3, 5, 3, 4, 4, 3, 0, 0, 0, 1, 1, 0],
                             [16, 15, 4, 8, 2, 1, 1, 3, 2, 2, 0, 0, 1, 0],
                             [13, 4, 19, 1, 6, 4, 7, 3, 0, 0, 1, 3, 0, 1],
                             [31, 8, 2, 25, 0, 0, 0, 0, 1, 0, 0, 2, 0, 0],
                             [6, 5, 7, 4, 4, 3, 2, 0, 0, 0, 0, 1, 0, 0],
                             [18, 2, 6, 4, 3, 5, 1, 0, 0, 0, 0, 0, 0, 0],
                             [4, 2, 11, 2, 2, 2, 12, 0, 2, 0, 0, 1, 0, 1],
                             [5, 1, 5, 5, 3, 6, 5, 5, 0, 0, 0, 1, 0, 0],
                             [6, 5, 0, 5, 1, 1, 0, 1, 2, 3, 0, 0, 0, 0],
                             [6, 5, 6, 1, 0, 0, 0, 0, 1, 3, 0, 1, 0, 0],
                             [5, 2, 6, 3, 2, 1, 2, 1, 1, 1, 1, 0, 0, 0],
                             [2, 2, 2, 1, 4, 1, 2, 1, 0, 0, 0, 5, 0, 1],
                             [2, 3, 3, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0],
                             [0, 0, 1, 0, 4, 0, 2, 0, 0, 0, 0, 0, 0, 5]])
# Extract values from the confusion matrix
true_positive = np.diag(conf_matrix)
false_positive = np.sum(conf_matrix, axis=0) - true_positive
false_negative = np.sum(conf_matrix, axis=1) - true_positive
true_negative = np.sum(conf_matrix) - (true_positive + false_positive + false_negative)

# Calculate Sensitivity (Recall)
sensitivity = true_positive / (true_positive + false_negative)

# Calculate Specificity
specificity = true_negative / (true_negative + false_positive)

# Display the results
print(f"Sensitivity (Recall): {sensitivity}")
print(f"Specificity: {specificity}")


Sensitivity (Recall): [0.43262411 0.26470588 0.27741935 0.23448276 0.13207547 0.11650485
 0.15740741 0.06896552 0.06122449 0.16       0.04255319 0.11538462
 0.025      0.55813953]
Specificity: [0.78322926 0.91563055 0.84462511 0.90778872 0.90916955 0.94909405
 0.94280763 0.96170213 0.98351195 0.97937294 0.99506173 0.98677686
 0.99918167 0.96800656]
